"""Add TenderIQ Analyze tables

Revision ID: 48317806289f
Revises: 3e7f2c1a9d4b
Create Date: 2025-11-05 13:11:09.386320

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import pgvector
from pgvector.sqlalchemy import Vector


# revision identifiers, used by Alembic.
revision: str = '48317806289f'
down_revision: Union[str, Sequence[str], None] = '3e7f2c1a9d4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tender_analyses',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tender_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'processing', 'completed', 'failed', name='analysisstatusenum'), nullable=True),
    sa.Column('progress', sa.Integer(), nullable=True),
    sa.Column('current_step', sa.String(length=50), nullable=True),
    sa.Column('analysis_type', sa.String(length=50), nullable=True),
    sa.Column('include_risk_assessment', sa.Boolean(), nullable=True),
    sa.Column('include_rfp_analysis', sa.Boolean(), nullable=True),
    sa.Column('include_scope_of_work', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('started_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('processing_time_ms', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tender_analyses_completed_at'), 'tender_analyses', ['completed_at'], unique=False)
    op.create_index(op.f('ix_tender_analyses_created_at'), 'tender_analyses', ['created_at'], unique=False)
    op.create_index(op.f('ix_tender_analyses_status'), 'tender_analyses', ['status'], unique=False)
    op.create_index(op.f('ix_tender_analyses_tender_id'), 'tender_analyses', ['tender_id'], unique=False)
    op.create_index(op.f('ix_tender_analyses_user_id'), 'tender_analyses', ['user_id'], unique=False)
    op.create_table('analysis_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('summary_json', sa.JSON(), nullable=True),
    sa.Column('rfp_analysis_json', sa.JSON(), nullable=True),
    sa.Column('scope_of_work_json', sa.JSON(), nullable=True),
    sa.Column('one_pager_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['tender_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_results_analysis_id'), 'analysis_results', ['analysis_id'], unique=True)
    op.create_table('analysis_rfp_sections',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('section_number', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('key_requirements', sa.JSON(), nullable=True),
    sa.Column('estimated_complexity', sa.String(length=20), nullable=False),
    sa.Column('compliance_status', sa.String(length=20), nullable=True),
    sa.Column('compliance_issues', sa.JSON(), nullable=True),
    sa.Column('related_sections', sa.JSON(), nullable=True),
    sa.Column('document_references', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['tender_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_rfp_sections_analysis_id'), 'analysis_rfp_sections', ['analysis_id'], unique=False)
    op.create_table('analysis_risks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('analysis_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.Enum('low', 'medium', 'high', 'critical', name='risklevelenum'), nullable=False),
    sa.Column('category', sa.Enum('regulatory', 'financial', 'operational', 'contractual', 'market', name='riskcategoryenum'), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('impact', sa.String(length=20), nullable=False),
    sa.Column('likelihood', sa.String(length=20), nullable=False),
    sa.Column('mitigation_strategy', sa.Text(), nullable=True),
    sa.Column('recommended_action', sa.Text(), nullable=True),
    sa.Column('related_documents', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['analysis_id'], ['tender_analyses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_analysis_risks_analysis_id'), 'analysis_risks', ['analysis_id'], unique=False)
    op.alter_column('dms_documents', 'is_tender_file',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.alter_column('dms_documents', 'is_cached',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('idx_dms_documents_cache_status'), table_name='dms_documents')
    op.drop_index(op.f('idx_dms_documents_scraped_tender_file_id'), table_name='dms_documents')
    op.drop_index(op.f('idx_dms_documents_tender_file'), table_name='dms_documents')
    op.drop_index(op.f('idx_scrape_runs_release_date'), table_name='scrape_runs')
    op.create_index(op.f('ix_scrape_runs_tender_release_date'), 'scrape_runs', ['tender_release_date'], unique=False)
    op.drop_index(op.f('idx_file_cache_status'), table_name='scraped_tender_files')
    op.drop_index(op.f('idx_file_dms_path'), table_name='scraped_tender_files')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_file_dms_path'), 'scraped_tender_files', ['dms_path'], unique=False)
    op.create_index(op.f('idx_file_cache_status'), 'scraped_tender_files', ['cache_status'], unique=False)
    op.drop_index(op.f('ix_scrape_runs_tender_release_date'), table_name='scrape_runs')
    op.create_index(op.f('idx_scrape_runs_release_date'), 'scrape_runs', ['tender_release_date'], unique=False)
    op.create_index(op.f('idx_dms_documents_tender_file'), 'dms_documents', ['is_tender_file'], unique=False)
    op.create_index(op.f('idx_dms_documents_scraped_tender_file_id'), 'dms_documents', ['scraped_tender_file_id'], unique=False)
    op.create_index(op.f('idx_dms_documents_cache_status'), 'dms_documents', ['cache_status'], unique=False)
    op.alter_column('dms_documents', 'is_cached',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.alter_column('dms_documents', 'is_tender_file',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('false'))
    op.drop_index(op.f('ix_analysis_risks_analysis_id'), table_name='analysis_risks')
    op.drop_table('analysis_risks')
    op.drop_index(op.f('ix_analysis_rfp_sections_analysis_id'), table_name='analysis_rfp_sections')
    op.drop_table('analysis_rfp_sections')
    op.drop_index(op.f('ix_analysis_results_analysis_id'), table_name='analysis_results')
    op.drop_table('analysis_results')
    op.drop_index(op.f('ix_tender_analyses_user_id'), table_name='tender_analyses')
    op.drop_index(op.f('ix_tender_analyses_tender_id'), table_name='tender_analyses')
    op.drop_index(op.f('ix_tender_analyses_status'), table_name='tender_analyses')
    op.drop_index(op.f('ix_tender_analyses_created_at'), table_name='tender_analyses')
    op.drop_index(op.f('ix_tender_analyses_completed_at'), table_name='tender_analyses')
    op.drop_table('tender_analyses')
    # ### end Alembic commands ###
